micronaut:
  application:
    name: keymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanager:
      address: ${ADDRESS_KEYMANAGER:localhost:50051}
      plaintext: true
      max-retry-attempts: 5

jackson:
  serialization:
    writeDatesAsTimestamps: false